language: php
sudo: false

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
      dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

install: composer install

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
